# Use uma imagem oficial do Node.js como base para o build
FROM node:18 AS build

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o código da aplicação para o container
COPY ./frontend . 

# Instale as dependências
RUN npm install

# Builda a aplicação para produção
RUN npm run build

# Use uma imagem do Node.js para a produção do Next.js
FROM node:18 AS production

# Defina o diretório de trabalho para a produção
WORKDIR /app

# Copie o diretório buildado para o contêiner de produção
COPY --from=build /app /app

# Exponha a porta 3000 (padrão do Next.js)
EXPOSE 8080

# Defina a variável de ambiente para o ambiente de produção
ENV NODE_ENV=production

# Comando para iniciar o servidor Next.js
CMD ["npm", "run", "start"]
