FROM node:18-alpine AS builder

WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend .

RUN npm run build

FROM node:18-alpine AS runner

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

ENV NODE_ENV=production
ENV HOST=0.0.0.0


COPY ./local/env ./local/env

CMD ["/bin/sh", "-c", "if [ -f ./local/env ]; then . ./local/env; fi && npm run start"]
