# Etapa de build
FROM node:18 AS builder
WORKDIR /app
COPY ./frontend . 
RUN npm install && npm run build

# Etapa final para servir o front-end
FROM nginx:alpine
# Certifique-se de criar o diretório antes de copiar
RUN mkdir -p /usr/share/nginx/html
COPY --from=builder /app/.next /usr/share/nginx/html
COPY --from=builder /app/public /usr/share/nginx/html/public
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
