FROM python:3.11-slim
WORKDIR /app
COPY backend/fastlog/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/fastlog/src/ /app/src/
EXPOSE 8000
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]